#!/bin/bash

makelinks(){
# Test if vimrc symbolic link exists
  if test -h "$HOME/.vimrc" 
  then
    echo "vimrc symbolic link already exists";
  else
     #Check and remove current .vimrc if its already there
     if test -e "$HOME/.vimrc" 
     then 
          rm "$HOME/.vimrc";
     fi
     $(
       cd "$HOME" || exit && echo "cd failed";
       ln -s "$HOME/repos/dot/.vimrc" .vimrc;
       echo "vimrc symbolic link created";
     )
  fi

# Test if bashrc symbolic link exists
  if test -h "$HOME/.bashrc"
  then
    echo "bashrc symbolic link already exists"
  else
     if test -e "$HOME/.bashrc" 
     then 
          rm "$HOME/.bashrc";
     fi
     $(
        cd "$HOME" || exit && echo "cd failed";
        ln -s "$HOME/repos/dot/.bashrc" .bashrc;
        echo "bashrc symbolic link created";
       )
  fi

# Test if dircolors symbolic link exists
  if test -h "$HOME/.dircolors"
  then
    echo "dircolors symbolic link already exists"
  else
     if test -e "$HOME/.dircolors" 
     then 
          rm "$HOME/.dircolors";
     fi
     $(
        cd "$HOME" || exit && echo "cd failed";
        ln -s "$HOME/repos/dot/.dircolors" .dircolors;
        echo "dircolors symbolic link created";
       )
  fi
}

main(){
  makelinks
}

main "$@"


