#!/usr/bin/bash

declare -a COMMANDS=(foo bar blah)
#----------------------------- Completion --------------------------
# complete -C completiontest completiontest - Use this program to do completion
# All completion logic goes here
if [[ -n $COMP_LINE ]]; then
  for c in ${COMMANDS[@]}; do
    [[ ${c:0:${#2}} = $2 ]] && echo "$c"
  done
  exit
fi
#--------------------------- End Completion ------------------------



