#!/bin/bash

tmux_status_right_cycle(){
  source weather -cm home > "/home/stremler/repos/dot/scripts/.tmuxoutput"
  cat "$HOME/repos/dot/scripts/.tmuxoutput"
}

main(){
  tmux_status_right_cycle
}

main 
