#!/bin/bash

declare -a COMMANDS=(current -c  help)
#----------------------------- Completion --------------------------
# complete -C completiontest completiontest - Use this program to do completion
# All completion logic goes here
if [[ -n $COMP_LINE ]]; then
  for c in ${COMMANDS[@]}; do
    [[ ${c:0:${#2}} = $2 ]] && echo "$c"
  done
  exit
fi
#--------------------------- End Completion ------------------------
current_minimized=false
yellow="\e[0;33m"
green="\e[0;32m"
reset_color="\e[m"
#Weather api at openweathermap.org. Pull the API key from env variables

if test -z "$WEATHER_API"; then 
  printf "%s\n" "Weather API environment variable isn't currently set"
  exit 1
fi
#------------------------------- Call API ---------------------------------
curr_weather_at_location(){
    curl -s GET "api.openweathermap.org/data/2.5/weather?zip={$1},us&units=imperial&appid={$WEATHER_API}" | jq "." |
      (
          result="$(cat)"
          name="$(echo "$result" | jq ".name")"
          temp="$(echo "$result" | jq ".main.temp")"
          feels_like="$(echo "$result" | jq ".main.feels_like")"
          condition="$(echo "$result" | jq ".weather[].main?")"
          humidity="$(echo "$result" | jq ".main.humidity")"
          wind_speed="$(echo "$result" | jq ".wind.speed")"
          wind_gust="$(echo "$result" | jq ".wind.gust")"
          sunrise="$(echo "$result" | jq ".sys.sunrise" | (temp_to_convert_sunrise="$(cat)"; date -d @"$temp_to_convert_sunrise" ))"
          sunset="$(echo "$result" | jq ".sys.sunset" | (temp_to_convert_sunset="$(cat)"; date -d @"$temp_to_convert_sunset"))"
          printf " %bLocation:%b%s\n %bTemperature:%b%s°F\n %bFeels Like:%b%s°F\n %bCondition:%b%s\n %bHumidity:%b%s%%\n %bWind Speed:%b%s\n %bWind Gust:%b%s\n %bSunrise:%b%s\n %bSunset:%b%s\n" \
          "$yellow" "$reset_color" "$name" \
          "$green" "$reset_color" "$temp" \
          "$yellow" "$reset_color" "$feels_like" \
          "$green" "$reset_color" "$condition" \
          "$yellow" "$reset_color" "$humidity" \
          "$green" "$reset_color" "$wind_speed" \
          "$yellow" "$reset_color" "$wind_gust" \
          "$green" "$reset_color" "$sunrise" \
          "$yellow" "$reset_color" "$sunset"; exit 0
     ) 
}

short_curr_weather_at_location(){
    curl -s GET "api.openweathermap.org/data/2.5/weather?zip={$1},us&units=imperial&appid={$WEATHER_API}" | jq "." |
      (   
          result="$(cat)"
          temp="$(echo "$result" | jq ".main.temp")"
          condition="$(echo "$result" | jq ".weather[].main?")"
          printf "Temp:%s°F Condition:%s" \
          "$temp" \
          "$condition"; exit 0
     )   
}

#------------------------------- Shortcuts --------------------------------
shortcut_check(){
  home_zip="48198"
  tim_zip="19102"
  dave_zip="94559"

  if test "$1" == "home"; then
    if test "$current_minimized" = true; then
      short_curr_weather_at_location "$home_zip" 
      exit 0
    fi
    curr_weather_at_location "$home_zip"
    exit 0
  fi
  
  if test "$1" == "tim"; then
    curr_weather_at_location "$tim_zip"
    exit 
  fi

  if test "$1" == "dave"; then
    curr_weather_at_location "$dave_zip"
    exit
  else
    printf "%s\n" "'$1' is not a valid shortcut."
    exit 1
  fi
}
#------------------------------ Run Command -------------------------------
rc(){
  # If weather command is called with no args then print "help" to show commands
  if test "$#" -eq 0 -o "$#" -eq 1 -a "$1" = "help"; then
    _help
    exit 0
  fi 

  if test "$1" = "current" -o "$1" = "curr" -o  "$1" = "-c"; then
    shift 1
    if [[ $1 =~ ^[A-Z]?[a-z]+$ ]]; then
      shortcut_check "$@"
    fi
    curr_weather_at_location "$@"
  fi
  if test "$1" = "-cm"; then
    shift 1
    current_minimized=true
    if [[ $1 =~ ^[A-Z]?[a-z]+$ ]]; then
      shortcut_check "$@"
    fi
  fi
}
# Print possible commands related to weather
_help(){
  printf "%s\n" "Usage:weather ([current | -c] | help)"
}
#--------------------------------- Main -----------------------------------
main(){
 rc "$@"
}

main "$@"
